config/routes.rb
Spina::Engine.routes.draw do

  # Backend
  namespace :admin do
    root to: "pages#index"

    resource :account do
      member do
        get :style
        get :analytics
        get :social
      end
    end

    resources :users

    # Sessions
    resources :sessions
    get "login" => "sessions#new"
    get "logout" => "sessions#destroy"

    # Media library
    get 'media_library' => 'photos#index', as: "media_library"

    resources :pages do
      post :sort, on: :collection
    end

    resources :page_parts do
      collection do
        get 'wysihtml5_link/:object_id' => 'page_parts#wysihtml5_link', as: :wysihtml5_link
        post 'wysihtml5_link/:object_id' => 'page_parts#insert_wysihtml5_link'
      end
    end

    resources :attachments do
      collection do
        get 'select/:page_part_id' => 'attachments#select', as: :select
        post 'insert/:page_part_id' => 'attachments#insert', as: :insert
        get 'select_collection/:page_part_id' => 'attachments#select_collection', as: :select_collection
        post 'insert_collection/:page_part_id' => 'attachments#insert_collection', as: :insert_collection
      end
    end

    resources :photos do
      collection do
        get 'wysihtml5_select/:object_id' => 'photos#wysihtml5_select', as: :wysihtml5_select
        post 'wysihtml5_insert/:object_id' => 'photos#wysihtml5_insert', as: :wysihtml5_insert
        get 'photo_select/:page_part_id' => 'photos#photo_select', as: :photo_select
        get 'photo_collection_select/:page_part_id' => 'photos#photo_collection_select', as: :photo_collection_select
        post 'insert_photo/:page_part_id' => 'photos#insert_photo', as: :insert_photo
        post 'insert_photo_collection/:page_part_id' => 'photos#insert_photo_collection', as: :insert_photo_collection
      end
      member do
        post :enhance
        get :link
      end
    end

    resources :inquiries, only: [:index, :show, :destroy] do
      collection do
        get :inbox
        get :spam
      end
      member do
        get :inbox_show
        patch :mark_as_read
        patch :unmark_spam
      end
    end
  end

  # Inquiries
  resources :inquiries

  # Sitemap
  resource :sitemap

  # Robots.txt
  get '/robots', to: 'pages#robots', format: :txt

  # Frontend
  root to: "pages#homepage"

  get ':root/:subpage/:id' => "pages#show", as: "third_level_page"
  get ':root/:id' => "pages#show", as: "subpage"
  get ':id' => "pages#show", as: "page"
end

app/models/spina/photo.rb
module Spina
  class Photo < ActiveRecord::Base
    mount_uploader :file, PhotoUploader

    has_many :page_parts, as: :page_partable
    has_many :photo_collections_photos
    has_many :photo_collections, through: :photo_collections_photos

    scope :sorted, -> { order('created_at DESC') }
    scope :sorted_by_photo_collection, -> { order('position') }

    validates_presence_of :file

    def name
      file.file.filename
    end

    def content
      self
    end
    
  end
end

app/controllers/spina/admin/photos_controller.rb
module Spina
  module Admin
    class PhotosController < AdminController
      before_filter :set_breadcrumbs
      
      authorize_resource class: Photo

      layout "spina/admin/media_library"

      def index
        add_breadcrumb "Afbeeldingen", spina.admin_photos_path
        @photos = Photo.sorted
        @photo = Photo.new
      end

      def create
        @photo = Photo.create(photo_params)
      end

      def destroy
        @photo = Photo.find(params[:id])
        @photo.destroy
        redirect_to spina.admin_photos_url
      end

      def enhance
        @photo = Photo.find(params[:id])
        @photo.remote_file_url = params[:new_image]
        @photo.save
      end

      def link
        @photo = Photo.find(params[:id])
      end

      def photo_select
        @photos = Photo.sorted
        @photo = Photo.new
        @selected_photo = Photo.find(params[:selected_photo_id]) if params[:selected_photo_id]
      end

      def photo_collection_select
        @photos = Photo.sorted
        @photo = Photo.new
        @selected_photos = params[:selected_photo_ids] ? Photo.where(id: params[:selected_photo_ids]) : Photo.none
      end

      def insert_photo
        @photo = Photo.find(params[:photo_id]) if params[:photo_id].present?
      end

      def insert_photo_collection
        @photos = Photo.find(params[:photo_ids]) if params[:photo_ids].present?
      end

      def wysihtml5_insert
        @photo = Photo.find(params[:photo_id])
      end

      def wysihtml5_select
        @photos = Photo.sorted
        @photo = Photo.new
      end

      private

      def set_breadcrumbs
        add_breadcrumb "Mediabibliotheek", spina.admin_media_library_path
      end

      def photo_params
        params.require(:photo).permit(:file)
      end
      
    end
  end
end

app/helpers/spina/admin/photos_helper.rb
module Spina
  module Admin
    module PhotosHelper
    end
  end
end

app/views/spina/admin/photos/_photo.html.haml
.item
  .overlay
    = radio_button_tag :photo_id, photo.id
    = check_box_tag 'photo_ids[]', photo.id
    = link_to '', admin_photo_path(photo), class: 'icon-only', data: {icon: 'Z', aviary: true}
    = link_to '', spina.admin_photo_path(photo), method: :delete, class: 'icon-only', data: {icon: 'Q', confirm: "Weet je zeker dat je deze <strong>foto</strong> wilt verwijderen?"}
  = image_tag photo.file.thumb.url, id: "photo_#{photo.id}", data: {posturl: spina.enhance_admin_photo_path(photo), image: photo.file.url}

app/views/spina/admin/photos/_photo_collection.html.haml
- if photos.present?
  %ul.sortable-grid
    - photos.each do |photo|
      %li.image{data: {photo_id: photo.id}}
        = image_tag photo.file.thumb

app/views/spina/admin/photos/_photo_collection_select.html.haml
.modal.modal-large
  %header
    = link_to "", "#", class: 'close_modal', data: {dismiss: 'modal', icon: 'm'}
    %h3 Afbeeldingen invoegen

  %section
    .gallery-select.gallery{data: {multiselect: true}}
      .item
        = form_for [spina, :admin, @photo], html: {multipart: true} do |f|
          = f.file_field :file, data: {customfileinput: true}
          
      = form_tag spina.insert_photo_collection_admin_photos_path(params[:page_part_id]), remote: true, class: 'gallery-prepend-image' do
        - @photos.each do |photo|
          .item{class: ('selected' if @selected_photos.include?(photo))}
            .overlay= check_box_tag 'photo_ids[]', photo.id, @selected_photos.include?(photo)
            = image_tag photo.file.thumb

        %footer
          = link_to "Annuleren", "#", data: {dismiss: 'modal'}
          = button_tag "Afbeeldingen invoegen", type: 'submit', class: 'primary', data: {icon: 't '}

app/views/spina/admin/photos/_photo_link.html.haml
#modal.modal
  %header.big-header
    = link_to '#', class: 'close_modal', data: {dismiss: 'modal'} do
      %i.icon-only{data: {icon: 'm'}}

    %h3
      De link naar de afbeelding is:
      %strong= @photo.file.url

  %footer
    = link_to 'Venster sluiten', '#', data: {dismiss: 'modal'}, style: 'width: 100%'

app/views/spina/admin/photos/_photo_select.html.haml
.modal.modal-large
  %header
    = link_to "", "#", class: 'close_modal', data: {dismiss: 'modal', icon: 'm'}
    %h3 Afbeelding invoegen

  %section
    .gallery-select.gallery
      .item
        = form_for [spina, :admin, @photo], html: {multipart: true} do |f|
          = f.file_field :file, data: {customfileinput: true}

      = form_tag spina.insert_photo_admin_photos_path(params[:page_part_id]), remote: true, class: 'gallery-prepend-image' do
        - @photos.each do |photo|
          .item{class: ('selected' if photo == @selected_photo)}
            .overlay= radio_button_tag :photo_id, photo.id, photo == @selected_photo
            = image_tag photo.file.thumb

        %footer
          = link_to "Annuleren", "#", data: {dismiss: 'modal'}
          = button_tag "Afbeelding invoegen", type: 'submit', class: 'primary', data: {icon: 't '}

app/views/spina/admin/photos/_wysihtml5_select.html.haml
.modal.modal-large
  %header
    = link_to "", "#", class: 'close_modal', data: {dismiss: 'modal', icon: 'm'}
    %h3 Afbeelding invoegen

  %section
    .gallery-select.gallery
      .item
        = form_for [spina, :admin, @photo], html: {multipart: true} do |f|
          = f.file_field :file, data: {customfileinput: true}

      = form_tag spina.wysihtml5_insert_admin_photos_path(params[:object_id]), remote: true, class: 'gallery-prepend-image' do
        - @photos.each do |photo|
          .item
            .overlay= radio_button_tag :photo_id, photo.id
            = image_tag photo.file.thumb

        %footer
          = link_to "Annuleren", "#", data: {dismiss: 'modal'}
          = button_tag "Afbeelding invoegen", type: 'submit', class: 'primary', data: {icon: 't '}

app/views/spina/admin/photos/index.html.haml
.gallery
  .item
    = form_for [spina, :admin, @photo], html: {multipart: true} do |f|
      = f.file_field :file, data: {customfileinput: true}

  .gallery-prepend-image
    = render partial: 'spina/admin/photos/photo', collection: @photos

app/views/spina/admin/photos/insert_photo.js.erb
var hidden_input = $("input[name='<%= j params[:page_part_id] %>[page_partable_id]']");
hidden_input.parents('td').find('a .image, a .placeholder').remove();
<% if @photo.present? %>
  hidden_input.parents('td').find('a').prepend("<div class='placeholder pull-right'><span class='button button-small button-round' data-icon='U'>Foto kiezen</span></div><div class='image'><img src='<%= @photo.file.thumb %>' /></div>");
  hidden_input.val("<%= @photo.id %>");
<% else %>
  hidden_input.parents('td').find('a').prepend("<div class='placeholder'><span class='button button-small button-round' data-icon='U'>Foto kiezen</span></div>");
  hidden_input.parents('td').append("<input type='hidden' type='checkbox' name='<%= j params[:page_part_id] %>[_destroy]' value='1' />")
<% end %>
$.hideModal();

app/views/spina/admin/photos/insert_photo_collection.js.erb
var hidden_input = $("input[name='<%= j params[:page_part_id] %>[photo_tokens]']");

<% if @photos.present? %>
  var photo_collection = $("<%= j render partial: 'photo_collection', locals: {photos: @photos} %>");
  hidden_input.parents('td').find('.photo-collection').html(photo_collection);
  hidden_input.parents('td').find('a .placeholder').addClass('pull-right');
  hidden_input.val("<%= @photos.map(&:id).join(',') %>");
<% else %>
  hidden_input.parents('td').find('a .placeholder').removeClass('pull-right');
  hidden_input.val("");
<% end %>

$('.sortable-grid').sortable('destroy');
$('.sortable-grid').sortable().bind('sortupdate', function(e) {
  position_array = [];
  $(e.target).find('li.image').each(function(index) {
    position_array.push($(this).data('photo-id'));
  });
  $(e.target).parents('td').find('.photo-positions').val(position_array.join(","));
});
$('.sortable-grid').trigger('sortupdate');

$.hideModal();

app/views/spina/admin/photos/link.js.erb
var modal = "<%=j render 'photo_link' %>";
$(modal).modal();

app/views/spina/admin/photos/photo_collection_select.js.erb
var modal = $("<%= j render 'photo_collection_select' %>");
modal.modal();

app/views/spina/admin/photos/photo_select.js.erb
var modal = $("<%= j render 'photo_select' %>");
modal.modal();

app/views/spina/admin/photos/wysihtml5_insert.js.erb
var editor = $(".wysihtml5-container[data-object-id=<%= params[:object_id] %>]").data('wysihtml5');
editor.focus();
editor.composer.commands.exec("insertHTML", "<img src='<%= @photo.file.url %>' />");
editor.focus();
$.hideModal();

app/views/spina/admin/photos/wysihtml5_select.js.erb
var modal = $("<%= j render 'wysihtml5_select' %>");
modal.modal();